language: python
dist: xenial
sudo: true

python:
  - 3.7

env:
  global:
    PIPENV_VENV_INpROJECT=1
    PIPENV_IGNORE_VIRTUALENVS=1

install:
  - pip install pipenv
  - pipenv sync -d

script:
  - pipenv run flake8 .
  - pipenv run pytest --cov=pypro

after_cuccess:
  - pipenv run codecov