language: python
dist: xenial
sudo: true

python:
  - 3.7

services:
  postgresql
addons:
  postgressql: '9.5'
env:
  global:
    PIPENV_VENV_INpROJECT=1
    PIPENV_IGNORE_VIRTUALENVS=1

install:
  - pip install pipenv
  - pipenv sync -d
  - cp contrib/env-sample .env

before_script:
  - psql -c "CREATE DATABASE testdb;" -U postgres

script:
  - pipenv run flake8 .
  - pipenv run pytest --cov=pypro

after_cuccess:
  - pipenv run codecov